### ISSUE TITLE
enhancement: Remove the need of explicitly passing a DataModel in order to read from Postgres

### ISSUE THREAD

**Issue by miodohelper** [miodo/dynamicio#2]
### Context

The dynamicio repo should be able to infer the input data `model` schema from the [schema yml files](https://github.com/miodo/dynamicio/blob/3694785473/demo/resources/schemas/input/bar.yaml), rather than requiring that the schema also be defined here: [BarDataModel](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/demo/src/io.py#L60).

Further Details can be found [here](https://youtu.be/A1MMF1SKIGI)

### Task
Remove the need for the [BarDataModel](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/demo/src/io.py#L60) class to be injected, [as seen here](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/demo/src/runners/staging.py#L19).

### Suggested Approach

Use the `sources_config`[link](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/dynamicio/mixins.py#L649) attribute to generate the `model`[link](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/dynamicio/mixins.py#L675)

### Acceptance Criteria

- [ ] dynamicio can infer the postgres schema from input yamls
- [ ] dynamicio does not accept a `model` argument [here](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/demo/src/runners/staging.py#L19)
- [ ] all existing tests pass
- [ ] new tests written as required
- [ ] readme & docs are updated to reflect the new changes.

### Expected Duration
4hrs
